name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Ensure correct directories exist
      run: mkdir -p ./android_client/app/src/main/res/layout ./android_client/app/src/main/res/values

    - name: Build Debug APK
      working-directory: ./android_client
      run: gradle assembleDebug --stacktrace

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OBS_Virtual_Camera_APK
        path: android_client/app/build/outputs/apk/debug/app-debug.apk
